language: python
python:
- '3.4'
install:
- pip3 install git+git://github.com/home-assistant/home-assistant.git
script:
- hass -c . --script check_config
before_install:
- mv travis_secrets.yaml secrets.yaml
notifications:
  slack:
    rooms:
      secure: C3KgoTdjKDuN50EVC3EATUZuU/15gf/LBKQ209OfVo2WEtgP1BSKbdWlFuobBRwZ//hJHCZ4j0vLIbNs7Q439mMjCU4ALxHsYQAtK8ptBUb8IQRO/FyR3chm72+M5JSVtxg44Z3Fjj1d9SlX7yWVhJW9VTvbeRCVainXgJ5OLkqe9lcj8WwInvzTOCkZ3H6ck3wt3k9aWy6g7s4pO3gg6j2QS84F2+xGXqXvRqfBxxUZ+sAJK6zqBPkW7Iki66Nnzg6Fg7/dCUJRFtvo/43filGffq2IGdzz09ACrsZp6iaRKUcsGM0raX6y3ZHgKdrDmxbwivzdH/mlb7rye/+NxAT8y4dcuAN94xfwG06/2Yf2oiJPhICWXnO9dBYlbQpl9QsF7xF1tNHLJEAMwrxlymdXdk6vMxgG0X62uXsS8RmOHzYqfa55b8fkWYTTm0ENewHQaW+L1vdTbjzY3orwYYt7XPdVPOTDXXjoXsos25f6yPg/n4lpBB8GDMSquxmWbclMDu0AGarCQx3Wd4nEXogy6r7SvNlzqivgfkauehCltSBh7QImCuvs0B7h8hvr/Jj59WFyRNOK2C3YwiTR6Z/Drn5eQSRHY8+AOe98EF1rgLxA3n5MGIiTEYbPcHSJiKYIv7iIe1dYx08a/NRL+XP0HK/oPXD07/yXpFv8W3g=
    template:
    - Status=%{result}, Job=%{repository_name}, Build=%{build_number}, URL=%{build_url}
