language: python
python:
  - "3.4"
install:
  #- pip3 install homeassistant
  - pip3 install git+git://github.com/home-assistant/home-assistant.git
script:
  - hass -c . --script check_config
before_install:
  - mv travis_secrets.yaml secrets.yaml
notifications:
  slack:
    rooms:
      - bargelt:r8ZuK4YKz8rPmOfPZ07pFF49#general
    template:
      - "Status=%{result}, Job=%{repository_name}, Build=%{build_number}, URL=%{build_url}"
