homeassistant:
  auth_providers:
    - type: homeassistant
    - type: legacy_api_password
      api_password: !secret api_password

#default_config:
automation:
config:
frontend:
history:
logbook:
map:
mobile_app:
person:
script:
sun:
system_health:
# updater:
zeroconf:

lovelace:
  mode: yaml

emulated_hue:

wemo:
  static:
    - 10.0.0.196

http:
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  login_attempts_threshold: 3
  base_url: !secret externaldomain

mqtt:
  broker: !secret ipaddress

device_tracker:
  - platform: unifi
    host: !secret router_ipaddress
    username: !secret unifi_controller_username
    password: !secret unifi_controller_password
    verify_ssl: false
    ssid_filter:
      - 'NSA Surveillance #22'

input_boolean: !include_dir_merge_named inputbools
weblink: !include includes/weblinks.yaml

tuya:
  username: !secret tuya_username
  password: !secret tuya_password
  country_code: 1
  platform: smart_life

  
ios:
  push:
    categories:
      - name: Alarm
        identifier: 'alarm'
        actions:
          - identifier: 'SILENCE_ALARM'
            title: 'Silence Alarm'
            activationMode: 'background'
            authenticationRequired: no
            destructive: yes
            behavior: 'default'
      - name: Siren
        identifier: 'siren'
        actions:
          - identifier: 'ACTIVATE_SIRENS'
            title: 'Activate Sirens'
            activationMode: 'background'
            authenticationRequired: no
            destructive: yes
            behavior: 'default' 

influxdb:
  host: !secret ipaddress
  database: homeassistant
  username: !secret influxdb_username
  password: !secret influxdb_password
  tags:
    instance: prod
    source: ha

sensor: !include_dir_merge_list sensors

zone:
  - name: Steve Work Bothell
    latitude: 47.774100
    longitude: -122.181513
    radius: 250
  - name: Steve Work Bellevue
    latitude: 47.613516
    longitude: -122.194069
    radius: 100

#######################################################
#####     TESTING AREA BELOW                      #####
#######################################################

weather:
- platform: darksky
  api_key: !secret darksky_key

alexa_media:
  accounts:
    - email: !secret amazon_user
      password: !secret amazon_password
      url: amazon.com
      exclude_devices:
       - "Steve's Alexa Apps"
       - "Steve's 2nd Fire"
       - "Steve's Fire"

notify:
  - platform: alexa_media
    name: alexa_media