homeassistant:
  name: Bargelt Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 273
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include_dir_merge_named customizations

zone:
  name: home
  latitude: !secret latitude
  longitude: !secret longitude
  radius: 200
  icon: mdi:home

http:
  api_password: !secret api_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  login_attempts_threshold: 3
  base_url: !secret externaldomain

frontend:
config:
updater:
discovery:
# history:
# logbook:
sun:
wemo:
ios:
logger:
  default: warn

zwave:
  usb_path: /zwaveusbstick

emulated_hue:
  type: alexa

ifttt:
  key: !secret ifttt_key

sensor: !include_dir_merge_list sensors
automation: !include_dir_merge_list automations
script: !include_dir_merge_named scripts
input_boolean: !include_dir_merge_named inputbools
input_select: !include_dir_merge_named inputselects
group: !include_dir_merge_named groups
scene: !include_dir_merge_list scene
weblink: !include includes/weblinks.yaml

mqtt:
  broker: !secret ipaddress

switch:
  - platform: mqtt
    name: "Water Kettle"
    state_topic: "ha/waterkettle"
    command_topic: "ha/waterkettle"
    qos: 0
    payload_on: "ON"
    payload_off: "OFF"
    optimistic:
    false retain: true

influxdb:
  host: !secret ipaddress
  database: homeassistant
  username: !secret influxdb_username
  password: !secret influxdb_password
  tags:
    instance: prod
    source: ha

device_tracker:
  - platform: owntracks
    max_gps_accuracy: 200


#######################################################
#####     TESTING AREA BELOW                      #####
#######################################################

#recorder:
  #purge_days: 1
  #db_url: !secret my_db

# panel_iframe:
#   download:
#     title: 'Download Speed'
#     url: !secret grafanadownload
#   upload:
#     title: 'Upload Speed'
#     url: !secret grafanaupload

tts:
  - platform: amazon_polly
    aws_access_key_id: !secret aws_access_key_id 
    aws_secret_access_key: !secret aws_secret_access_key
    region_name: 'us-east-1'
    voice: 'Salli'

media_player:
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret

light:
  - platform: mqtt_json
    name: "Kitchen Accent"
    state_topic: "ha/kitchenaccent"
    command_topic: "ha/kitchenaccent/set"
    effect: true
    effect_list: [fire, rainbow, solid]
    brightness: true
    flash: true
    rgb: true
    optimistic: false
    qos: 0

# input_slider:
#   kitchen_animation_speed:
#     name: Kitchen Animation Speed
#     initial: 150
#     min: 1
#     max: 150
#     step: 10

