homeassistant:
  name: Bargelt Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 273
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include_dir_merge_named customizations

http:
  api_password: !secret api_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  login_attempts_threshold: 3

frontend:
config:
updater:
discovery:

sun:
wemo:
  static:
    - 192.168.1.215

history:
logbook:

# Text to speech
tts:
  platform: google

zwave:
  usb_path: /zwaveusbstick

emulated_hue:

ifttt:
  key: !secret ifttt_key

device_tracker:
  - platform: locative

sensor: !include_dir_merge_list sensors
automation: !include_dir_merge_list automations
script: !include_dir_merge_named scripts
group: !include_dir_merge_named groups
