homeassistant:
  name: Bargelt Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 273
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include_dir_merge_named customizations

http:
  api_password: !secret api_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  login_attempts_threshold: 3
  base_url: !secret externaldomain

frontend:
config:
updater:
discovery:
sun:
wemo:
ios:
logger:
  default: warn

zwave:
  usb_path: /zwaveusbstick

emulated_hue:
  type: alexa

ifttt:
  key: !secret ifttt_key