homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret my_latitude
  longitude: !secret my_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 273
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret api_password
  # Uncomment this if you are using SSL or running in Docker etc
  #base_url: 
  ssl_certificate: !secret my_ssl_certificate
  ssl_key: !secret my_ssl_key

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

wemo:
  static:
    - 192.168.1.215

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor:
  platform: yr

# Text to speech
tts:
  platform: google

zwave:
  usb_path: /zwaveusbstick

emulated_hue:

device_tracker:
  - platform: asuswrt
    host: 192.168.1.1
    username: !secret asus_username
    password: !secret asus_password
  - platform: icloud
    username: !secret icloud_username
    password: !secret icloud_password
    account_name: Steven Randall

group: !include groups.yaml
