homeassistant:
  name: Bargelt Home
  latitude: !secret my_latitude
  longitude: !secret my_longitude
  elevation: 273
  unit_system: imperial
  time_zone: America/Chicago

frontend:

http:
  api_password: !secret api_password
  ssl_certificate: !secret my_ssl_certificate
  ssl_key: !secret my_ssl_key
  login_attempts_threshold: 3

# Checks for available updates
updater:
discovery:
sun:
wemo:
  static:
    - 192.168.1.215

history:

logbook:

sensor: !include_dir_merge_list sensor

# Text to speech
tts:
  platform: google

zwave:
  usb_path: /zwaveusbstick

emulated_hue:

ifttt:
  key: !secret ifttt_key
  
device_tracker:
  - platform: asuswrt
    host: 192.168.1.1
    username: !secret asus_username
    password: !secret asus_password
  - platform: icloud
    username: !secret icloud_username
    password: !secret icloud_password
    account_name: Steven Randall

group: !include groups.yaml
