version: '3.1'
services:
  mqtt-ext:
    image: mosquitto-rpi
    restart: always
    ports: 
      - "8083:8083"
      - "8883:8883"
    volumes:
        - /etc/letsencrypt:/etc/letsencrypt
        - /home/pi/homeassistant/mosquitto-ext.conf:/mosquitto/config/mosquitto.conf
        - /etc/ssl/certs/DST_Root_CA_X3.pem:/mosquitto/DST_Root_CA_X3.pem
        - /home/pi/homeassistant/pwfile:/etc/mosquitto/pwfile
        - /mosquitto/data
        - /mosquitto/log
  mqtt-int:
    image: mosquitto-rpi
    restart: always
    depends_on:
      - mqtt-ext
    ports: 
      - "1883:1883"
    volumes:
        - /home/pi/homeassistant/mosquitto-int.conf:/mosquitto/config/mosquitto.conf
        - /etc/ssl/certs/DST_Root_CA_X3.pem:/mosquitto/DST_Root_CA_X3.pem
        - /mosquitto/data 
        - /mosquitto/log

  influxdb:
    image: hypriot/rpi-influxdb
    restart: always
    ports:
      - "8086:8086"
    volumes:
      #- /home/pi/influxdb:/var/lib/influxdb
      - /home/pi/influxdb:/data
  grafana:
    image: pithings/rpi-grafana
    restart: always 
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
    volumes: 
      - /home/pi/grafana:/var/lib/grafana
  # db:
  #   image: hypriot/rpi-mysql:5.5
  #   restart: always
  #   volumes:
  #     - /home/pi/homeassistant/mysql:/var/lib/mysql
  #   ports:
  #     - "3306:3306"
  #   secrets:
  #     - mysqlrootpassword
  #     - mysqlpassword
  #   environment:
  #     MYSQL_ROOT_PASSWORD: "/run/secrets/mysqlrootpassword"
  #     MYSQL_PASSWORD: "/run/secrets/mysqlpassword"      
  #     MYSQL_DATABASE: 'homeassistant'
  #     MYSQL_USER: 'hass'

  home-assistant:
    image: homeassistant/raspberrypi-homeassistant
    restart: always
    depends_on:
      - mqtt-int
      - influxdb
      # - db
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /home/pi/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    devices:
      - "/dev/ttyUSB0:/zwaveusbstick:rwm"
    network_mode: "host"

# secrets:
#   mysqlrootpassword:
#     file: ./mysqlrootpassword.txt
#   mysqlpassword:
#     file: ./mysqlpassword.txt
