version: '3.1'
services:
  home-assistant:
    image: homeassistant/raspberrypi3-homeassistant
    restart: always
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /home/pi/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    devices:
      - "/dev/ttyUSB0:/zwaveusbstick:rwm"
    network_mode: "host"