version: '3.1'
services:
  home-assistant:
    image: homeassistant/raspberrypi3-homeassistant
    restart: always
    volumes:
      - /home/pi/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    network_mode: "host"