version: '3.7'
services:
  mqtt-int:
    image: eclipse-mosquitto
    restart: unless-stopped
    environment:
      - TZ=America/Los_Angeles
    ports: 
      - "1883:1883"
    volumes:
        - /Users/steve/ha/home-assistant-config/mosquitto-int.conf:/mosquitto/config/mosquitto.conf
        - /Users/steve/ha/mosquitto/data:/mosquitto/data
        - /Users/steve/ha/mosquitto/log:/mosquitto/log
  influxdb:
    image: influxdb
    restart: unless-stopped
    environment:
      - TZ=America/Los_Angeles
    ports:
      - "8086:8086"
    volumes:
      #- /home/pi/influxdb:/var/lib/influxdb
      - /Users/steve/ha/influxdb:/data
  grafana:
    image: grafana/grafana
    restart: unless-stopped
    environment:
      - TZ=America/Los_Angeles
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
    volumes: 
      - /Users/steve/ha/grafana:/var/lib/grafana
  
  home-assistant:
    image: homeassistant/home-assistant
    restart: unless-stopped
    depends_on:
      - mqtt-int
      - influxdb
    environment:
      - TZ=America/Los_Angeles
    ports:
      - "8123:8123"
    volumes:
      - /Users/steve/ha/letsencrypt:/etc/letsencrypt
      - /Users/steve/ha/home-assistant-config:/config

  node-red:
    image: nodered/node-red-docker
    restart: unless-stopped
    depends_on:
      - home-assistant    
    environment:
      - TZ=America/Los_Angeles
    ports:
      - "1880:1880"
    volumes: 
      - /Users/steve/ha/node-red-data:/data

  esphome:
    image: esphome/esphome
    restart: unless-stopped
    depends_on:
      - home-assistant    
    environment:
      - ESPHOME_DASHBOARD_USE_PING="true"
      - TZ=America/Los_Angeles
    ports:
      - "8266:8266"
      - "3232:3232"
      - "6052:6052"
      - "5353:5353"
    volumes:
      - /Users/steve/ha/esphome:/config

  # dasher:
  #   image: nekmo/amazon-dash:latest  
  #   volumes:
  #     - /Users/steve/ha/dasher/config:/usr/src/app/config
  #   entrypoint:
  #     - amazon-dash run 
  #     - --ignore-perms 
  #     - --root-allowed
  #     - --config /config/amazon-dash.yml

