- platform: systemmonitor
  resources:
    # - type: last_boot
    - type: since_last_boot
    - type: disk_use_percent
      arg: /

- platform: speedtest
  monitored_conditions:
    - ping
    - download
    - upload
