- platform: darksky
  api_key: !secret darksky_key
  monitored_conditions:
    - precip_type
    - precip_intensity
    - precip_intensity_max
    - temperature
    - wind_speed
    - cloud_cover
    - humidity
    - nearest_storm_distance
    - minutely_summary

- platform: moon