- platform: xbox_live
  api_key: b1f57e5e97b89cf1d887e048ec962a0c40f2f986
  xuid: 
    - !secret deity_xuid
    - !secret juggerbird_xuid
    - !secret pinkwolf_xuid
    - !secret wifey_xuid

- platform: history_stats
  name: Deity Xbox
  entity_id: sensor.deity
  state: 'Online'
  type: time
  start: '{{ as_timestamp( now().replace(hour=0).replace(minute=0).replace(second=0) ) - now().weekday() * 86400 }}'
  end: '{{ now() }}'

- platform: history_stats
  name: Zoe Xbox
  entity_id: sensor.pinkwolf300
  state: 'Online'
  type: time
  start: '{{ as_timestamp( now().replace(hour=0).replace(minute=0).replace(second=0) ) - now().weekday() * 86400 }}'
  end: '{{ now() }}'