- platform: bayesian
  prior: 0.5
  name: "Bayesian Presence Steve"
  device_class: 'presence'
  probability_threshold: 0.9
  observations:
    # iOS App
    - entity_id: "device_tracker.steves_11_pro_max"
      prob_given_true: 0.9
      prob_given_false: 0.2
      platform: 'state'
      to_state: 'home'
    # Tile on Keys (I can leave keys at home if Maggie drives)
    - entity_id: "device_tracker.tile_bce880b97d7c4949"
      prob_given_true: 0.8
      prob_given_false: 0.4
      platform: 'state'
      to_state: 'home'
