- platform: template
  sensors:
    motion_front_door:
      friendly_name: Camera Front Door
      device_class: motion
      entity_id: camera.front_door
      value_template: "{{ is_state('camera.front_door', 'motion') }}"
      delay_off: 
          seconds: 30
