#####################################################################
#  Some home facts
#####################################################################
- alias: 'Home Stats'

  trigger:
    - platform: state
      entity_id:
        - group.family_home
      from: 'off'
      to: 'on'
      for: '00:05:00'

    - platform: state
      entity_id: input_boolean.home_stats
      to: 'on'
      from: 'off'

  action:
    - service: input_boolean.turn_on
      entity_id:
        - input_boolean.outside_weather
        - input_boolean.lights_status

    - service: script.speech_engine
      data:
        call_responsibilities: 1
        call_outside_weather: 1
        call_light_check: 1  