- alias: 'Away Mode'
  trigger:
    - platform: state
      entity_id: group.family_home
      to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'

  action:
    - service: script.interior_off
    - service: script.ifttt_notify
      data_template:
        value1: 'Away Mode Activated'
        value2: 'Group Family - is not home'