######################################################################
##  Morning Routine
######################################################################

- alias: 'Morning Routine'
  trigger:
    - platform: state
      entity_id: input_boolean.good_morning
      state: 'on'
      from: 'off'

  # condition:
  #   - condition: state
  #     entity_id: group.family
  #     state: home

  action:
    - service: switch.turn_on
      entity_id:
        - switch.kitchen_overhead
        - switch.steve_lamp_switch_4_0
        - switch.water_kettle
        
    - service: input_boolean.turn_off
      entity_id: input_boolean.good_morning
    - service: tts.amazon_polly_say
      data:
        entity_id: media_player.bedroon
        message: 'Good Morning. I hope you have a great day.'