######################################################################
##  Morning Routine
######################################################################

- alias: 'Morning Routine'
  trigger:
    - platform: state
      entity_id: input_boolean.good_morning
      state: 'on'
      from: 'off'

  # condition:
  #   - condition: state
  #     entity_id: group.family
  #     state: home

  action:
    - service: switch.turn_on
      entity_id:
        - switch.kitchen_lights
        - switch.master_bedroom_lights
        - switch.water_kettle
        
    - service: input_boolean.turn_off
      entity_id: input_boolean.good_morning