# The idea is that ALL (both right now) trackers have to be 'not home' to 
#   flip the input.boolean.maggiehome to off (away)
#   and ANY tracker set to 'home' will flip input.boolean.maggiehome to on (home)
- alias: 'Mark Maggie Away'
  condition:
    condition: state
    entity_id: input_boolean.maggiehome
    state: 'on'
  trigger:
    platform: template
    value_template: "{% if (is_state('device_tracker.margarets_iphone','not_home')) and (is_state('device_tracker.owntracksuser_maggieiphone','not_home')) %}true{% endif %}"
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.maggiehome

- alias: 'Mark Maggie Home'
  condition:
    condition: state
    entity_id: input_boolean.maggiehome
    state: 'off'
  trigger:
    - platform: state
      entity_id: device_tracker.margarets_iphone
      to: 'home' 
    - platform: state
      entity_id: device_tracker.owntracksuser_maggieiphone #owntracks
      to: 'home'
  action:
     service: homeassistant.turn_on
     entity_id: input_boolean.maggiehome