# device_tracker.steveiphone : iPhone from HA on phone
# device_tracker.owntracksuser_steveiphone : from OwnTracks
# The idea is that ALL (both right now) trackers have to be 'not home' to 
#   flip the input.boolean.stevehome to off (away)
#   and ANY tracker set to 'home' will flip input.boolean.stevehome to on (home)
- alias: 'Mark Steve Away'
  condition:
    condition: state
    entity_id: input_boolean.stevehome
    state: 'on'
  trigger:
    platform: template
      value_template: "{% if (is_state('device_tracker.steveiphone','not_home')) and (is_state('device_tracker.owntracksuser_steveiphone','not_home')) %}true{% endif %}"
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.stevehome
- alias: 'Mark Steve Home'
  condition:
    condition: state
    entity_id: input_boolean.stevehome
    state: 'off'
  trigger:
    - platform: state
      entity_id: device_tracker.steveiphone #hass App on iPhone
      to: 'home' 
    - platform: state
      entity_id: device_tracker.owntracksuser_steveiphone #owntracks
      to: 'home'
  action:
     service: homeassistant.turn_on
     entity_id: input_boolean.stevehome